"""auto-vote

Revision ID: 042d4d9d2850
Revises: c90ccf1c0d4b
Create Date: 2022-06-22 17:42:34.345543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042d4d9d2850'
down_revision = 'c90ccf1c0d4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.add_column('posts', sa.Column('rating', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'rating')
    op.drop_table('votes')
    # ### end Alembic commands ###
